# Generated by Django 6.0.5 on 2026-07-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('aadhaar_photo', models.ImageField(blank=True, null=True, upload_to='customer/aadhaar/')),
                ('driving_license_number', models.CharField(blank=True, max_length=25)),
                ('driving_license_photo', models.ImageField(blank=True, null=True, upload_to='customer/license/')),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('aadhaar_photo', models.ImageField(blank=True, null=True, upload_to='owner/aadhaar/')),
                ('driving_license_number', models.CharField(blank=True, max_length=25)),
                ('driving_license_photo', models.ImageField(blank=True, null=True, upload_to='owner/license/')),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('ifsc_code', models.CharField(blank=True, max_length=15)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('profile_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
