# Generated by Django 6.0.5 on 2026-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Example: yourname@oksbi', max_length=100),
        ),
    ]
