from django.urls import path
from . import views

urlpatterns = [

    path(
        "book/<int:car_id>/",
        views.book_car,
        name="book_car",
    ),
    path(
    "my-bookings/",
    views.my_bookings,
    name="my_bookings",
    ),
    path(
    "details/<int:booking_id>/",
    views.booking_details,
    name="booking_details",
),
path(
    "cancel/<int:booking_id>/",
    views.cancel_booking,
    name="cancel_booking",
),
path(
    "owner-bookings/",
    views.owner_bookings,
    name="owner_bookings",
),
path(
    "owner-booking/<int:booking_id>/",
    views.owner_booking_details,
    name="owner_booking_details",
),
path(
    "approve/<int:booking_id>/",
    views.approve_booking,
    name="approve_booking",
),

path(
    "reject/<int:booking_id>/",
    views.reject_booking,
    name="reject_booking",
),
path(
    "owner-notifications/",
    views.owner_notifications,
    name="owner_notifications",
),
path(
    "admin-bookings/",
    views.admin_bookings,
    name="admin_bookings",
),
path(
    "admin-booking/<int:booking_id>/",
    views.admin_booking_details,
    name="admin_booking_details",
),
path(
    "export-bookings/",
    views.export_bookings_csv,
    name="export_bookings_csv",
),
path(
    "complete-booking/<int:booking_id>/",
    views.complete_booking,
    name="complete_booking",
),
path(
    "review/<int:booking_id>/",
    views.add_review,
    name="add_review",
),
path(
    "admin-reviews/",
    views.admin_reviews,
    name="admin_reviews",
),

path(
    "delete-review/<int:review_id>/",
    views.delete_review,
    name="delete_review",
),
path(
    "complete-booking/<int:booking_id>/",
    views.complete_booking,
    name="complete_booking",
),
path(
    "payment/<int:booking_id>/",
    views.payment_page,
    name="payment_page",
),
path(
    "payment-success/<int:booking_id>/",
    views.payment_success,
    name="payment_success",
),
path(
    "payment-failed/<int:booking_id>/",
    views.payment_failed,
    name="payment_failed",
),
path(
    "payments/",
    views.payment_history,
    name="payment_history",
),
path(
    "receipt/<int:payment_id>/",
    views.download_receipt,
    name="download_receipt",
),
path(
    "wallet/",
    views.wallet,
    name="wallet",
),
path(
    "wallet-payment/<int:booking_id>/",
    views.wallet_payment,
    name="wallet_payment",
),
]