# Generated by Django 6.0.5 on 2026-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
