# Generated by Django 6.0.5 on 2026-09-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='image',
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='carimage',
            name='image_type',
            field=models.CharField(default='image/jpeg', max_length=100),
        ),
    ]
