# Generated by Django 6.0.5 on 2026-07-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_coupon_booking_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_amount',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
