# Generated by Django 6.0.5 on 2026-07-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
