# Generated by Django 6.0.5 on 2026-07-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='owner_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
