# Generated by Django 6.0.5 on 2026-07-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_payment_commission_payment_owner_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
