# Generated by Django 6.0.5 on 2026-07-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_invoice_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
