# Generated by Django 6.0.5 on 2026-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='receiver',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Payment', 'Payment'), ('Wallet', 'Wallet'), ('Refund', 'Refund'), ('Coupon', 'Coupon'), ('Car', 'Car'), ('Verification', 'Verification'), ('System', 'System')], default='System', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
