# Generated by Django 6.0.5 on 2026-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_receiver_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Booking', 'Booking'), ('Payment', 'Payment'), ('Wallet', 'Wallet'), ('Coupon', 'Coupon'), ('System', 'System')], default='System', max_length=30),
        ),
    ]
